// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'account_token_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'account_token_model.g.dart';

@freezed
class AccountTokenModel with _$AccountTokenModel {
  const factory AccountTokenModel({
    @JsonKey(name: 'access_token') required String accessToken,
    @JsonKey(name: 'token_type') required String tokenType,
    @JsonKey(name: 'expires_in') required int expiresIn,
  }) = _AccountTokenModel;

  factory AccountTokenModel.fromJson(Map<String, Object?> json) =>
      _$AccountTokenModelFromJson(json);
}
