// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:spotify_playlist/models/artist_search_model.dart';
import 'package:spotify_playlist/models/image_url_model.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'album_search_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'album_search_model.g.dart';

@freezed
class AlbumSearchModel with _$AlbumSearchModel {
  const factory AlbumSearchModel({
    @JsonKey(name: 'album_type') required String albumType,
    @JsonKey(name: 'images') required List<ImageUrlModel> imagesList,
    @JsonKey(name: 'name') required String name,
    @JsonKey(name: 'artists') required List<ArtistSearchModel> artists,
  }) = _AlbumSearchModel;

  factory AlbumSearchModel.fromJson(Map<String, Object?> json) =>
      _$AlbumSearchModelFromJson(json);
}
