// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:spotify_playlist/models/artist_search_model.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'album_detail_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'album_detail_model.g.dart';

@freezed
class AlbumDetailModel with _$AlbumDetailModel {
  const factory AlbumDetailModel({
    @JsonKey(name: 'artists') required List<ArtistSearchModel> artists,
    @JsonKey(name: 'duration_ms') required int durationMs,
    @JsonKey(name: 'id') required String id,
    @JsonKey(name: 'name') required String name,
    @JsonKey(name: 'preview_url') required String previewUrl,
  }) = _AlbumDetailModel;

  factory AlbumDetailModel.fromJson(Map<String, Object?> json) =>
      _$AlbumDetailModelFromJson(json);
}
