// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:spotify_playlist/models/image_url_model.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'featured_playlist_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'featured_playlist_model.g.dart';

@freezed
class FeaturedPlaylistModel with _$FeaturedPlaylistModel {
  const factory FeaturedPlaylistModel({
    @JsonKey(name: 'id') required String id,
    @JsonKey(name: 'name') required String name,
    @JsonKey(name: 'description') required String description,
    @JsonKey(name: 'images') required List<ImageUrlModel> imagesList,
  }) = _FeaturedPlaylistModel;

  factory FeaturedPlaylistModel.fromJson(Map<String, Object?> json) =>
      _$FeaturedPlaylistModelFromJson(json);
}
