// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'image_url_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'image_url_model.g.dart';

@freezed
class ImageUrlModel with _$ImageUrlModel {
  const factory ImageUrlModel({
    @JsonKey(name: 'height') required int? height,
    @JsonKey(name: 'width') required int? width,
    @JsonKey(name: 'url') required String url,
  }) = _ImageUrlModel;

  factory ImageUrlModel.fromJson(Map<String, Object?> json) =>
      _$ImageUrlModelFromJson(json);
}
