// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'track_playlist_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'track_playlist_model.g.dart';

@freezed
class TrackPlaylistModel with _$TrackPlaylistModel {
  const factory TrackPlaylistModel({
    @JsonKey(name: 'href') required String href,
    @JsonKey(name: 'total') required int total,
  }) = _TrackPlaylistModel;

  factory TrackPlaylistModel.fromJson(Map<String, Object?> json) =>
      _$TrackPlaylistModelFromJson(json);
}
