// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:spotify_playlist/models/album_search_model.dart';
import 'package:spotify_playlist/models/artist_search_model.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'track_search_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'track_search_model.g.dart';

@freezed
class TrackSearchModel with _$TrackSearchModel {
  const factory TrackSearchModel({
    @JsonKey(name: 'id') required String id,
    @JsonKey(name: 'type') required String type,
    @JsonKey(name: 'album') required AlbumSearchModel album,
    @JsonKey(name: 'name') required String name,
    @JsonKey(name: 'artists') required List<ArtistSearchModel> artists,
    @JsonKey(name: 'duration_ms') required int durationMs,
    @JsonKey(name: 'uri') required String uri,
  }) = _TrackSearchModel;

  factory TrackSearchModel.fromJson(Map<String, Object?> json) =>
      _$TrackSearchModelFromJson(json);
}
